# Generated by Django 5.0 on 2024-12-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfoliocoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocoin',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
